add policy tree example
DoubleML/doubleml-docs pull request #150
Opened 2023-09-01 04:17 UTC by OliverSchacht

- Documentation is extended in 4. Heterogeneous Treatment Effects.
- Example for Policy Tree is added.

2023-09-04 09:54 UTC, SvenKlaassen requested changes

2023-09-04 09:54 UTC, SvenKlaassen commented on doc/guide/heterogeneity.rst
- False Heading level 4.4.3. This should be 4.5. Please use:
Policy Learning with Trees
+++++++++++++++++++++++

- Please add more explanation before the formula. E.g. Explain how a policy is defined
```math
\pi: X\mapsto \{0,1\},
```
what is optimized/maximized etc.
Remark that this is a deterministic policy.

2023-09-04 09:54 UTC, SvenKlaassen commented on doc/examples/py_double_ml_policy_tree.ipynb
- Please use
$$
\begin{aligned}
Y_i & = g(W_1,W_2)T_i + \langle W_i,\gamma_0\rangle + \epsilon_i \\
T_i & = \langle W_i,\beta_0\rangle +\eta_i,
\end{aligned}
$$
to display the alignment. Can you also adjust this in the GATE and CATE Notebook?

- Please use `print()` for pandas.DataFrame
- Please add more interpretation to the results. Why is it helpful that we know the true DGP? What is the ATTE for the policy

2023-09-05 19:48 UTC, OliverSchacht commented
Hi @SvenKlaassen 
thank you for your comments. I made the following changes:

- Extend the policy tree notebook, especially making comparisons between original DGP and estimated splits as well as comparison of original ATTE and optimal policy ATTE
- Extend documentation of Policy Tree optimization problem.

2023-09-06 05:51 UTC, SvenKlaassen approved these changes

2023-09-08 13:28 UTC, merged